version: "3.9"

services:
  django:
    build:
      context: ./Backend
    container_name: sabiway_web
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://sabiway_db_user:OCuy82gn8IBsGMMijEeHjgLjYidGiAug@dpg-d42adk15pdvs73f3oh5g-a.oregon-postgres.render.com/sabiway_db"
      SECRET_KEY: "replace-this-in-production"
      DEBUG: "True"

  express:
    build:
      context: ./ExpressJs
    container_name: express_app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
