version: '3.9'

services:
  web:
    build: .
    container_name: sabiway_web
    command: gunicorn sabiway.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      SECRET_KEY: "insecure-secret"
      ALLOWED_HOSTS: "localhost,127.0.0.1,sabiway-9wq4.onrender.com"

      # Google OAuth
      GOOGLE_CLIENT_ID: "62853499803-r7kkbq52ptk4u2j5mralkbbkquen4chh.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"

      # Resend API
      RESEND_API_KEY: "re_cV9BwHsi_GDtS6kPGHrTnJGpwD5Vf6HNQ"
      DEFAULT_FROM_EMAIL: "SabiWay <info@sabiway.com>"

      # URLs
      BACKEND_URL: "http://localhost:8000"
      FRONTEND_URL: "http://localhost:3000"

      # Cloudinary
      CLOUDINARY_CLOUD_NAME: "devqbjptr"
      CLOUDINARY_API_KEY: "233511915335819"
      CLOUDINARY_API_SECRET: "ZcbD-lTO22KamDmTWMhp-xPgLxU"

      # Database settings
      DB_ENGINE: "django.db.backends.mysql"
      DB_NAME: "sabiway_db"
      DB_USER: "sabiway_user"
      DB_PASSWORD: "sabiway_pass"
      DB_HOST: "db"
      DB_PORT: "3306"

  db:
    image: mysql:8.0
    container_name: sabiway_db
    restart: always
    environment:
      MYSQL_DATABASE: sabiway_db
      MYSQL_USER: sabiway_user
      MYSQL_PASSWORD: sabiway_pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
