"use client";

import { FormEvent, useState } from "react";
import { BriefcaseBusiness, CheckCircle2, Clock3, MapPin, MessageCircle, Search, SlidersHorizontal } from "lucide-react";

import { environment } from "@/app/config/environment";

export type MarketplaceCategory = { id: number; name: string; slug: string; description: string; icon?: string; subcategories?: { id: number; name: string; slug: string }[] };
export type MarketplaceListing = { id: string; title: string; description: string; price_from: string; currency: string; pricing_note?: string; delivery_mode: "in_person" | "remote" | "both"; country?: string; state: string; city?: string; area: string; availability_text?: string; available_now?: boolean; is_featured?: boolean; moderation_status?: string; provider: { user_id?: number; full_name: string; username: string; job?: string | null; profile_picture?: string | null }; category: MarketplaceCategory; subcategory?: { id: number; name: string; slug: string } | null };
export type MarketplaceJob = { id: string; title: string; description: string; budget_min?: string | null; budget_max?: string | null; currency: string; delivery_mode: "in_person" | "remote" | "both"; country?: string; state?: string; city?: string; area?: string; needed_by?: string | null; response_count: number; client: { user_id?: number; full_name: string; username: string }; category: MarketplaceCategory };

type JobResponsePayload = { id: string };
type ThreadPayload = { id: string };
type Props = { initialListings: MarketplaceListing[]; initialJobs: MarketplaceJob[]; categories: MarketplaceCategory[] };
type Tab = "services" | "jobs";
type Paginated<T> = T[] | { results?: T[] };

const inputClass = "min-h-12 w-full rounded-xl border border-[#d9e4dd] bg-white px-4 text-sm text-[#173126] outline-none transition focus:border-[#008753] focus:ring-2 focus:ring-[#008753]/15";
const categoryGlyphs = ["⚡", "🔧", "🧹", "✂", "💄", "📚", "💻", "🛠"];
function unwrap<T>(payload: Paginated<T>): T[] { return Array.isArray(payload) ? payload : payload.results ?? []; }

export default function MarketplaceClient({ initialListings, initialJobs, categories }: Props) {
  const [tab, setTab] = useState<Tab>("services");
  const [listings, setListings] = useState(initialListings);
  const [jobs, setJobs] = useState(initialJobs);
  const [query, setQuery] = useState("");
  const [location, setLocation] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("");
  const [selectedListing, setSelectedListing] = useState<MarketplaceListing | null>(null);
  const [selectedJob, setSelectedJob] = useState<MarketplaceJob | null>(null);
  const [showOfferService, setShowOfferService] = useState(false);
  const [showPostJob, setShowPostJob] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [startingConversation, setStartingConversation] = useState(false);
  const [searching, setSearching] = useState(false);

  const accessToken = () => typeof window === "undefined" ? null : window.localStorage.getItem("access");
  const requireAccess = () => { const access = accessToken(); if (!access) window.location.href = "/login?next=/marketplace"; return access; };

  async function searchMarketplace(overrides?: { category?: string; query?: string; location?: string }) {
    const q = (overrides?.query ?? query).trim(); const place = (overrides?.location ?? location).trim(); const category = overrides?.category ?? categoryFilter;
    const params = new URLSearchParams(); if (q) params.set("q", q); if (place) params.set("location", place); if (category) params.set("category", category); const suffix = params.size ? `?${params.toString()}` : "";
    setSearching(true); setError("");
    try {
      const [listingResponse, jobResponse] = await Promise.all([fetch(`${environment.djangoUrl}/api/marketplace/listings/${suffix}`, { cache: "no-store" }), fetch(`${environment.djangoUrl}/api/marketplace/jobs/${suffix}`, { cache: "no-store" })]);
      if (!listingResponse.ok || !jobResponse.ok) throw new Error("Marketplace search is temporarily unavailable.");
      const [listingPayload, jobPayload] = await Promise.all([listingResponse.json(), jobResponse.json()]); setListings(unwrap<MarketplaceListing>(listingPayload)); setJobs(unwrap<MarketplaceJob>(jobPayload));
    } catch (searchError) { setError(searchError instanceof Error ? searchError.message : "Could not search the marketplace. Please try again."); }
    finally { setSearching(false); }
  }

  async function postService(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const access = requireAccess(); if (!access) return; const data = new FormData(event.currentTarget); setError(""); setNotice("");
    const response = await fetch(`${environment.djangoUrl}/api/marketplace/listings/`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${access}` }, body: JSON.stringify({ category_id: Number(data.get("category_id")), title: data.get("title"), description: data.get("description"), price_from: data.get("price_from"), pricing_note: data.get("pricing_note"), currency: "NGN", delivery_mode: data.get("delivery_mode"), country: data.get("country"), state: data.get("state"), city: data.get("city"), area: data.get("area"), availability_text: data.get("availability_text"), available_now: data.get("available_now") === "on" }) });
    const payload = await response.json().catch(() => ({})); if (!response.ok) { setError(payload.detail || payload.non_field_errors?.[0] || "Could not submit your service."); return; } setListings((current) => [payload as MarketplaceListing, ...current]); setNotice("Service submitted for review."); event.currentTarget.reset();
  }

  async function postJob(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const access = requireAccess(); if (!access) return; const data = new FormData(event.currentTarget); setError(""); setNotice("");
    const response = await fetch(`${environment.djangoUrl}/api/marketplace/jobs/`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${access}` }, body: JSON.stringify({ category_id: Number(data.get("category_id")), title: data.get("title"), description: data.get("description"), budget_min: data.get("budget_min") || null, budget_max: data.get("budget_max") || null, currency: "NGN", delivery_mode: data.get("delivery_mode"), country: data.get("country"), state: data.get("state"), city: data.get("city"), area: data.get("area"), needed_by: data.get("needed_by") || null }) });
    const payload = await response.json().catch(() => ({})); if (!response.ok) { setError(payload.detail || payload.non_field_errors?.[0] || "Could not post your job."); return; } setJobs((current) => [payload as MarketplaceJob, ...current]); setNotice("Job submitted for review."); event.currentTarget.reset();
  }

  async function startListingConversation(listing: MarketplaceListing) {
    const access = requireAccess(); if (!access) return; setStartingConversation(true); setError("");
    try { const response = await fetch(`${environment.djangoUrl}/api/marketplace/threads/`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${access}` }, body: JSON.stringify({ listing_id: listing.id }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setError(payload.non_field_errors?.[0] || payload.detail || "Could not start conversation."); return; } window.location.href = `/messages?thread=${(payload as ThreadPayload).id}`; }
    finally { setStartingConversation(false); }
  }

  async function respondToJob(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selectedJob) return; const access = requireAccess(); if (!access) return; const data = new FormData(event.currentTarget); setError(""); setNotice(""); setStartingConversation(true);
    try { const response = await fetch(`${environment.djangoUrl}/api/marketplace/job-responses/`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${access}` }, body: JSON.stringify({ job_id: selectedJob.id, message: data.get("message"), proposed_price: data.get("proposed_price") || null, currency: "NGN" }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setError(payload.non_field_errors?.[0] || payload.detail || "Could not send your response."); return; } const threadResponse = await fetch(`${environment.djangoUrl}/api/marketplace/threads/`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${access}` }, body: JSON.stringify({ job_response_id: (payload as JobResponsePayload).id }) }); const threadPayload = await threadResponse.json().catch(() => ({})); if (!threadResponse.ok) { setNotice("Response sent. Open Messages when the conversation is available."); setSelectedJob(null); return; } window.location.href = `/messages?thread=${(threadPayload as ThreadPayload).id}`; }
    finally { setStartingConversation(false); }
  }

  const results = tab === "services" ? listings.length : jobs.length;

  return <main className="min-h-screen bg-[#f5f7f6] text-[#173126]">
    <section className="bg-[#008753] px-4 pb-16 pt-10 text-white sm:px-6 lg:px-8 lg:pb-20">
      <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.7fr] lg:items-end">
        <div><p className="text-xs font-black uppercase tracking-[.18em] text-white/70">SabiWay Marketplace</p><h1 className="mt-3 max-w-3xl text-4xl font-black leading-[1.03] tracking-[-.035em] sm:text-5xl lg:text-6xl">What do you need today?</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/82">Search trusted services, compare professionals and move directly into messaging, booking and protected payment.</p></div>
        <div className="rounded-[1.75rem] border border-white/10 bg-white/10 p-5 backdrop-blur"><p className="text-sm font-extrabold">Prefer to describe the work?</p><p className="mt-1 text-sm leading-6 text-white/75">Post a job and let relevant professionals respond.</p><button onClick={() => { setShowPostJob(true); setShowOfferService(false); }} className="mt-4 min-h-11 rounded-full bg-[#FFB800] px-5 text-sm font-black text-[#173126]">Post a Job</button></div>
      </div>
      <form onSubmit={(e) => { e.preventDefault(); void searchMarketplace(); }} className="mx-auto mt-8 grid max-w-7xl gap-2 rounded-2xl bg-white p-2 shadow-[0_18px_50px_rgba(0,0,0,.15)] md:grid-cols-[1.35fr_1fr_220px_auto]" role="search">
        <label className="relative"><span className="sr-only">Search</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#69786f]" size={18}/><input className={`${inputClass} border-0 pl-11 shadow-none`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search services or skills"/></label>
        <label className="relative"><span className="sr-only">Location</span><MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-[#69786f]" size={18}/><input className={`${inputClass} border-0 pl-11 shadow-none`} value={location} onChange={(e) => setLocation(e.target.value)} placeholder="City, state or area"/></label>
        <select aria-label="Category" className={`${inputClass} border-0 shadow-none`} value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}><option value="">All categories</option>{categories.map((c) => <option key={c.id} value={c.slug}>{c.name}</option>)}</select>
        <button disabled={searching} className="min-h-12 rounded-xl bg-[#008753] px-5 font-black text-white disabled:opacity-60">{searching ? "Searching…" : "Search"}</button>
      </form>
    </section>

    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <section><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#008753]">Popular Categories</p><h2 className="mt-1 text-2xl font-black">Start with a category</h2></div><button onClick={() => { setCategoryFilter(""); void searchMarketplace({ category: "" }); }} className="text-sm font-black text-[#008753]">See all</button></div>
        <div className="flex gap-5 overflow-x-auto pb-3 lg:grid lg:grid-cols-8 lg:overflow-visible">{categories.slice(0,8).map((category, index) => { const active = categoryFilter === category.slug; return <button key={category.id} onClick={() => { setCategoryFilter(active ? "" : category.slug); setTab("services"); void searchMarketplace({ category: active ? "" : category.slug }); }} className="min-w-[82px] text-center"><span className={`mx-auto flex h-16 w-16 items-center justify-center rounded-full border text-2xl transition ${active ? "border-[#008753] bg-[#dff7eb]" : "border-[#dce7e1] bg-white"}`}>{categoryGlyphs[index % categoryGlyphs.length]}</span><span className={`mt-2 block text-xs font-extrabold ${active ? "text-[#008753]" : "text-[#45564c]"}`}>{category.name}</span></button>; })}</div>
      </section>

      <section className="mt-8 grid gap-6 lg:grid-cols-[250px_1fr]">
        <aside className="hidden self-start rounded-2xl border border-[#dfe7e2] bg-white p-5 lg:block lg:sticky lg:top-6"><div className="flex items-center gap-2"><SlidersHorizontal size={18} className="text-[#008753]"/><h2 className="font-black">Filters</h2></div><label className="mt-5 block text-xs font-black uppercase tracking-wide text-[#68776f]">Location<input value={location} onChange={(e) => setLocation(e.target.value)} className={`${inputClass} mt-2`} placeholder="Any location"/></label><label className="mt-4 block text-xs font-black uppercase tracking-wide text-[#68776f]">Category<select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)} className={`${inputClass} mt-2`}><option value="">All</option>{categories.map((c) => <option key={c.id} value={c.slug}>{c.name}</option>)}</select></label><button onClick={() => void searchMarketplace()} className="mt-5 min-h-11 w-full rounded-xl bg-[#008753] font-black text-white">Apply filters</button><button onClick={() => { setLocation(""); setCategoryFilter(""); void searchMarketplace({ location: "", category: "" }); }} className="mt-2 min-h-10 w-full text-sm font-bold text-[#64746b]">Reset</button></aside>

        <div><div className="flex flex-col gap-4 border-b border-[#dce7e1] pb-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-6" role="tablist"><button role="tab" aria-selected={tab === "services"} onClick={() => setTab("services")} className={`border-b-2 px-1 pb-3 text-sm font-black ${tab === "services" ? "border-[#008753] text-[#008753]" : "border-transparent text-[#738079]"}`}>Services</button><button role="tab" aria-selected={tab === "jobs"} onClick={() => setTab("jobs")} className={`border-b-2 px-1 pb-3 text-sm font-black ${tab === "jobs" ? "border-[#008753] text-[#008753]" : "border-transparent text-[#738079]"}`}>Job Requests</button></div><div className="flex gap-2"><span className="self-center text-xs font-bold text-[#78857e]">{results} results</span><button onClick={() => { setShowPostJob((v) => !v); setShowOfferService(false); }} className="rounded-full border border-[#008753] px-4 py-2 text-sm font-black text-[#008753]">Post job</button><button onClick={() => { setShowOfferService((v) => !v); setShowPostJob(false); }} className="rounded-full bg-[#008753] px-4 py-2 text-sm font-black text-white">Offer service</button></div></div>

          {(showPostJob || showOfferService) && <div className="my-5 overflow-hidden rounded-2xl border border-[#dce7e1] bg-white"><div className="bg-[#008753] px-5 py-4 text-white"><p className="text-xs font-black uppercase tracking-[.15em]">{showPostJob ? "Client" : "Professional"}</p><h3 className="mt-1 text-xl font-black">{showPostJob ? "Post a Job" : "Offer a service"}</h3></div><form onSubmit={showPostJob ? postJob : postService} className="grid gap-3 p-5 md:grid-cols-2"><select name="category_id" required className={inputClass}><option value="">Choose category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input name="title" required className={inputClass} placeholder={showPostJob ? "Job title" : "Service title"}/><textarea name="description" required className={`${inputClass} min-h-28 py-3 md:col-span-2`} placeholder="Describe it clearly"/>{showPostJob ? <><input name="budget_min" type="number" min="0" className={inputClass} placeholder="Minimum budget (NGN)"/><input name="budget_max" type="number" min="0" className={inputClass} placeholder="Maximum budget (NGN)"/><input name="needed_by" type="date" className={inputClass}/></> : <><input name="price_from" required type="number" min="0" className={inputClass} placeholder="Starting price (NGN)"/><input name="pricing_note" className={inputClass} placeholder="Pricing note"/><input name="availability_text" className={inputClass} placeholder="Availability"/></>}<select name="delivery_mode" defaultValue="in_person" className={inputClass}><option value="in_person">In person</option><option value="remote">Remote</option><option value="both">In person or remote</option></select><input name="country" className={inputClass} placeholder="Country"/><input name="state" className={inputClass} placeholder="State"/><input name="city" className={inputClass} placeholder="City"/><input name="area" className={inputClass} placeholder="Area"/>{!showPostJob && <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="available_now"/> Available now</label>}<div className="flex gap-3 md:col-span-2"><button className="rounded-xl bg-[#008753] px-5 py-3 font-black text-white">Continue</button><button type="button" onClick={() => { setShowPostJob(false); setShowOfferService(false); }} className="rounded-xl border border-[#d6e0da] px-5 py-3 font-bold">Cancel</button></div></form></div>}
          {notice && <div className="my-4 flex items-center gap-2 rounded-xl bg-[#eaf8f1] p-4 text-sm font-bold text-[#006b42]" role="status"><CheckCircle2 size={18}/>{notice}</div>}{error && <div className="my-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700" role="alert">{error}</div>}

          {tab === "services" ? <div className="mt-5 grid gap-3 xl:grid-cols-2">{listings.map((listing) => <button key={listing.id} onClick={() => setSelectedListing(listing)} className="flex gap-4 rounded-2xl border border-[#e1e7e3] bg-white p-4 text-left transition hover:border-[#008753]/50 hover:shadow-sm"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl bg-[#e5ece8] text-2xl font-black text-[#008753]">{listing.provider.full_name.slice(0,1)}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="truncate font-black">{listing.provider.full_name}</h3><p className="mt-0.5 text-xs font-semibold text-[#68776f]">{listing.title}</p></div>{listing.available_now && <span className="rounded-full bg-[#e6f8ef] px-2 py-1 text-[10px] font-black text-[#008753]">Available</span>}</div><p className="mt-2 text-xs text-[#77837c]">{listing.category.name} · {[listing.area,listing.city,listing.state].filter(Boolean).join(", ") || "Flexible location"}</p><div className="mt-3 flex items-center justify-between"><p className="text-sm font-black">{listing.currency} {Number(listing.price_from).toLocaleString()}+</p><span className="text-xs font-black text-[#008753]">View profile →</span></div></div></button>)}</div> : <div className="mt-5 space-y-3">{jobs.map((job) => <button key={job.id} onClick={() => setSelectedJob(job)} className="w-full rounded-2xl border border-[#e1e7e3] bg-white p-5 text-left transition hover:border-[#008753]/50 hover:shadow-sm"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#e6f8ef] text-[#008753]"><BriefcaseBusiness size={19}/></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><h3 className="font-black">{job.title}</h3><span className="text-xs font-bold text-[#7c8881]">{job.response_count} responses</span></div><p className="mt-1 text-xs text-[#718078]">{job.category.name} · {[job.city,job.state].filter(Boolean).join(", ") || "Flexible location"}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#5f6f66]">{job.description}</p><div className="mt-3 flex items-center justify-between"><p className="font-black">{job.budget_min || job.budget_max ? `${job.currency} ${Number(job.budget_min || 0).toLocaleString()} – ${Number(job.budget_max || job.budget_min || 0).toLocaleString()}` : "Open to quote"}</p><span className="text-xs font-black text-[#008753]">View job →</span></div></div></div></button>)}</div>}
          {results === 0 && <div className="mt-5 rounded-2xl border border-dashed border-[#bfd2c7] bg-white p-10 text-center"><SlidersHorizontal className="mx-auto text-[#008753]"/><h3 className="mt-3 text-lg font-black">Nothing matches yet</h3><p className="mt-1 text-sm text-[#66756d]">Try another category, location or search term.</p></div>}
        </div>
      </section>
    </div>

    {selectedListing && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-3 sm:items-center"><div className="w-full max-w-2xl overflow-hidden rounded-[1.75rem] bg-white shadow-2xl" role="dialog" aria-modal="true"><div className="bg-[#008753] p-6 text-white"><button onClick={() => setSelectedListing(null)} className="float-right rounded-full bg-white/15 px-3 py-2 text-sm font-black">Close</button><p className="text-xs font-black uppercase tracking-[.15em] text-white/70">{selectedListing.category.name}</p><h2 className="mt-2 text-3xl font-black">{selectedListing.provider.full_name}</h2><p className="mt-1 text-white/80">{selectedListing.title}</p></div><div className="p-6"><p className="leading-7 text-[#5d6d64]">{selectedListing.description}</p><div className="mt-5 grid gap-3 rounded-2xl bg-[#f5f7f6] p-4 sm:grid-cols-2"><p className="flex items-center gap-2 text-sm"><MapPin size={16}/>{[selectedListing.area,selectedListing.city,selectedListing.state,selectedListing.country].filter(Boolean).join(", ") || "Flexible location"}</p>{selectedListing.availability_text && <p className="flex items-center gap-2 text-sm"><Clock3 size={16}/>{selectedListing.availability_text}</p>}<p className="text-lg font-black">{selectedListing.currency} {Number(selectedListing.price_from).toLocaleString()}+</p></div><button disabled={startingConversation} onClick={() => void startListingConversation(selectedListing)} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#008753] font-black text-white"><MessageCircle size={18}/>{startingConversation ? "Starting…" : "Message professional"}</button></div></div></div>}

    {selectedJob && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-3 sm:items-center"><div className="w-full max-w-2xl overflow-hidden rounded-[1.75rem] bg-white shadow-2xl" role="dialog" aria-modal="true"><div className="bg-[#008753] p-6 text-white"><button onClick={() => setSelectedJob(null)} className="float-right rounded-full bg-white/15 px-3 py-2 text-sm font-black">Close</button><p className="text-xs font-black uppercase tracking-[.15em] text-white/70">Job information</p><h2 className="mt-2 text-3xl font-black">{selectedJob.title}</h2></div><div className="p-6"><p className="leading-7 text-[#5d6d64]">{selectedJob.description}</p><div className="mt-4 flex flex-wrap gap-3 text-sm font-bold"><span>{[selectedJob.city,selectedJob.state,selectedJob.country].filter(Boolean).join(", ") || "Flexible location"}</span><span>·</span><span>{selectedJob.budget_min || selectedJob.budget_max ? `${selectedJob.currency} ${Number(selectedJob.budget_min || 0).toLocaleString()} – ${Number(selectedJob.budget_max || selectedJob.budget_min || 0).toLocaleString()}` : "Open to quote"}</span></div><form onSubmit={respondToJob} className="mt-5 space-y-3"><textarea name="message" required className={`${inputClass} min-h-32 py-3`} placeholder="Explain how you can help and your availability"/><input name="proposed_price" type="number" min="0" className={inputClass} placeholder="Your price (NGN, optional)"/><button disabled={startingConversation} className="w-full rounded-xl bg-[#008753] px-5 py-3 font-black text-white">{startingConversation ? "Starting conversation…" : "Send response"}</button></form></div></div></div>}
  </main>;
}
