import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0005_profile_rating_fields"),
        ("marketplace", "0005_phase5_messaging_booking"),
        ("sabipay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.CharField(choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("critical", "Critical")], default="normal", max_length=16)),
                ("response_due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("decision", models.CharField(blank=True, choices=[("", "Not decided"), ("release_full", "Release full payment"), ("refund_full", "Refund full payment"), ("partial", "Partial outcome")], max_length=24)),
                ("decision_reason", models.TextField(blank=True)),
                ("provider_release_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("client_refund_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_dispute_cases", to=settings.AUTH_USER_MODEL)),
                ("dispute", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="case", to="sabipay.dispute")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_dispute_cases", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "permissions": [("manage_trust_cases", "Can triage and resolve trust cases")]},
        ),
        migrations.AddIndex(model_name="disputecase", index=models.Index(fields=["priority", "response_due_at"], name="trust_dispute_sla_idx")),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("encrypted_payload", models.BinaryField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dispute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_items", to="sabipay.dispute")),
                ("uploader", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trust_evidence_uploads", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="DisputeNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("internal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="dispute_case_notes", to=settings.AUTH_USER_MODEL)),
                ("dispute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="case_notes", to="sabipay.dispute")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField(blank=True)),
                ("moderation_status", models.CharField(choices=[("published", "Published"), ("hidden", "Hidden pending review"), ("removed", "Removed")], default="published", max_length=16)),
                ("moderation_reason", models.TextField(blank=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="review", to="marketplace.bookingrequest")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reviews_written", to="profiles.profile")),
                ("moderated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="moderated_reviews", to=settings.AUTH_USER_MODEL)),
                ("professional", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reviews_received", to="profiles.profile")),
                ("transaction", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="review", to="sabipay.transaction")),
            ],
            options={"ordering": ["-created_at"], "permissions": [("moderate_reviews", "Can moderate marketplace reviews")]},
        ),
        migrations.AddIndex(model_name="review", index=models.Index(fields=["professional", "moderation_status", "created_at"], name="trust_review_prof_idx")),
        migrations.AddIndex(model_name="review", index=models.Index(fields=["rating", "created_at"], name="trust_review_rating_idx")),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=80)),
                ("details", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("reviewed", "Reviewed"), ("dismissed", "Dismissed"), ("actioned", "Actioned")], default="open", max_length=16)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_reports", to="profiles.profile")),
                ("review", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="trustops.review")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="review_reports_handled", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="reviewreport", constraint=models.UniqueConstraint(fields=("review", "reporter"), name="trust_review_reporter_uniq")),
        migrations.CreateModel(
            name="SupportCase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=80)),
                ("summary", models.CharField(max_length=180)),
                ("details", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In progress"), ("escalated", "Escalated"), ("resolved", "Resolved"), ("closed", "Closed")], default="open", max_length=20)),
                ("priority", models.CharField(choices=[("normal", "Normal"), ("high", "High"), ("critical", "Critical")], default="normal", max_length=16)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("response_due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_support_cases", to=settings.AUTH_USER_MODEL)),
                ("dispute", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_cases", to="sabipay.dispute")),
                ("escalated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="escalated_support_cases", to=settings.AUTH_USER_MODEL)),
                ("opened_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="support_cases", to="profiles.profile")),
                ("review", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_cases", to="trustops.review")),
                ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_cases", to="sabipay.transaction")),
            ],
            options={"ordering": ["-created_at"], "permissions": [("manage_support_cases", "Can manage support and escalation cases")]},
        ),
        migrations.AddIndex(model_name="supportcase", index=models.Index(fields=["status", "priority", "response_due_at"], name="trust_support_queue_idx")),
        migrations.CreateModel(
            name="SupportNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("internal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="support_notes", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="trustops.supportcase")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="SupportAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(max_length=80)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_audit_events", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="trustops.supportcase")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="FraudSignal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=80)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=16)),
                ("status", models.CharField(choices=[("open", "Open"), ("reviewed", "Reviewed"), ("dismissed", "Dismissed"), ("actioned", "Actioned")], default="open", max_length=16)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dispute", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fraud_signals", to="sabipay.dispute")),
                ("profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fraud_signals", to="profiles.profile")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fraud_signals_reviewed", to=settings.AUTH_USER_MODEL)),
                ("support_case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fraud_signals", to="trustops.supportcase")),
                ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fraud_signals", to="sabipay.transaction")),
            ],
            options={"ordering": ["-created_at"], "permissions": [("manage_fraud_signals", "Can review marketplace fraud signals")]},
        ),
        migrations.AddIndex(model_name="fraudsignal", index=models.Index(fields=["status", "severity", "created_at"], name="trust_fraud_queue_idx")),
    ]
