// AUTO-GENERATED by scripts/sync-design-tokens.mjs. Edit design-system/tokens.json instead.
export const designTokens = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "meta": {
    "name": "SabiWay V2 Design Tokens",
    "source": "Master Playbook + approved Ui Mobile App Design export + supplied branding",
    "version": 1
  },
  "primitive": {
    "color": {
      "green": "#008753",
      "greenStrong": "#006B42",
      "orange": "#FFB800",
      "white": "#FFFFFF",
      "neutral950": "#17211B",
      "neutral800": "#333333",
      "neutral600": "#637067",
      "neutral300": "#DDE7E1",
      "neutral100": "#F5F5F5",
      "green50": "#E8F7F0",
      "green100": "#DFF7EB",
      "green900": "#072419",
      "red600": "#C9362B",
      "blue600": "#2563EB"
    }
  },
  "semantic": {
    "color": {
      "light": {
        "background": "#F7FAF8",
        "surface": "#FFFFFF",
        "surfaceSubtle": "#F5F5F5",
        "text": "#17211B",
        "textMuted": "#637067",
        "border": "#DDE7E1",
        "primary": "#008753",
        "primaryStrong": "#006B42",
        "onPrimary": "#FFFFFF",
        "accent": "#FFB800",
        "onAccent": "#17211B",
        "success": "#008753",
        "warning": "#FFB800",
        "danger": "#C9362B",
        "info": "#2563EB",
        "focus": "#006B42"
      },
      "dark": {
        "background": "#0C1E16",
        "surface": "#12291E",
        "surfaceSubtle": "#193328",
        "text": "#F7FAF8",
        "textMuted": "#B8C8BF",
        "border": "#365044",
        "primary": "#38C987",
        "primaryStrong": "#67DEA3",
        "onPrimary": "#072419",
        "accent": "#FFCA45",
        "onAccent": "#17211B",
        "success": "#38C987",
        "warning": "#FFCA45",
        "danger": "#F87171",
        "info": "#60A5FA",
        "focus": "#67DEA3"
      }
    }
  },
  "typography": {
    "fontFamily": "Inter",
    "size": {
      "xs": 12,
      "sm": 14,
      "md": 16,
      "lg": 18,
      "xl": 20,
      "2xl": 24,
      "3xl": 30,
      "4xl": 36
    },
    "lineHeight": {
      "tight": 1.2,
      "normal": 1.5,
      "relaxed": 1.65
    },
    "weight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700
    }
  },
  "spacing": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64
  },
  "radius": {
    "sm": 8,
    "md": 12,
    "lg": 16,
    "xl": 20,
    "pill": 999
  },
  "elevation": {
    "sm": "0 1px 2px rgba(23, 33, 27, 0.08)",
    "md": "0 6px 18px rgba(23, 33, 27, 0.10)",
    "lg": "0 16px 40px rgba(23, 33, 27, 0.14)"
  },
  "interaction": {
    "minimumTouchTarget": 44,
    "focusRingWidth": 3
  },
  "breakpoint": {
    "xs": 320,
    "sm": 430,
    "md": 768,
    "lg": 1024,
    "xl": 1280,
    "2xl": 1440
  }
} as const;

const light = designTokens.semantic.color.light;

// Compatibility aliases let current screens migrate to semantic names incrementally.
export const colors = {
  ...light,
  brand: light.primary,
  brandStrong: light.primaryStrong,
  muted: light.textMuted,
} as const;
export const spacing = designTokens.spacing;
export const radius = designTokens.radius;
export const typography = designTokens.typography;
export const interaction = designTokens.interaction;
