export const TableOfContents = [
    { id: "acceptance", label: "ACCEPTANCE OF TERMS" },
    { id: "definitions", label: "DEFINITIONS" },
    { id: "eligibility", label: "ELIGIBILITY AND ACCOUNT REGISTRATION" },
    { id: "description", label: "DESCRIPTION OF SERVICES" },
    { id: "service", label: "SERVICE PROFESSIONAL TERMS" },
    { id: "customer", label: "CUSTOMER TERMS" },
    { id: "payments", label: "PAYMENTS AND FEES" },
    { id: "user_content", label: "USER CONTENT AND CONDUCT" },
    { id: "review", label: "REVIEWS AND RATINGS" },
    { id: "intellectual", label: "INTELLECTUAL PROPERTY" },
    { id: "disclaimers", label: "DISCLAIMERS AND LIMITATIONS OF LIABILITY" },
    { id: "indemnification", label: "INDEMNIFICATION" },
    { id: "dispute", label: "DISPUTE RESOLUTION " },
    { id: "termination", label: "TERM AND TERMINATION" },
    { id: "privacy", label: "PRIVACY AND DATA PROTECTION" },
    { id: "insurance", label: "INSURANCE AND LIABILITY COVERAGE" },
    { id: "background", label: "MODIFICATIONS TO TERMS" },
    { id: "general", label: "GENERAL PROVISIONS" },
    { id: "specific_terms", label: "SPECIFIC TERMS FOR SERVICE CATEGORIES" },
    { id: "feedback", label: "FEEDBACK AND SUGGESTIONS" },
    { id: "contact", label: "CONTACT INFORMATION" },
    { id: "acknowledgement", label: "ACKNOWLEDGMENT AND ACCEPTANCE" },
]