# sabiway/settings.py

"""
Django settings for sabiway project.

Generated by 'django-admin startproject' using Django 3.2.12.
"""

from pathlib import Path
import environ
import os
from datetime import timedelta
import dj_database_url

# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------
# Environment variables
# ---------------------------------------------------------------------
env = environ.Env(
    DEBUG=(bool, False)  # set casting and default
)

# Read .env file (create one in project root)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# ---------------------------------------------------------------------
# Core settings
# ---------------------------------------------------------------------
DEBUG = env("DEBUG", default="True")
SECRET_KEY = "insecure-secret"
# ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
#     "localhost",
#     "127.0.0.1",
#     "sabiway-9wq4.onrender.com",
# ])

ALLOWED_HOSTS = ['*']


# Google OAuth
GOOGLE_CLIENT_ID = "935346913786-bbafum8k8qk3l42g4ijg007ft31r0p1e.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

# For Resend API
RESEND_API_KEY = "re_cV9BwHsi_GDtS6kPGHrTnJGpwD5Vf6HNQ"
DEFAULT_FROM_EMAIL = "SabiWay <info@sabiway.com>"
ADMIN_REPORT_EMAIL = "sabiway1@gmail.com"

# ---------------------------------------------------------------------
# URLs
# ---------------------------------------------------------------------
# Use Docker environment variables if provided, otherwise fallback to defaults
# FRONTEND_URL = "http://localhost:3000"
# BACKEND_URL = "http://localhost:8000"
# EXPRESS_URL = "http://localhost:5000"


# FOR VPS
# FRONTEND_URL = "https://www.sabiway.com"
# BACKEND_URL = "https://django.sabiway.com"
# EXPRESS_URL = "https://express.sabiway.com"



# For Render
FRONTEND_URL = "https://www.sabiway.com"
BACKEND_URL = "https://backend.sabiway.com"
EXPRESS_URL = "https://realtime.sabiway.com"

# Half VPS
# FRONTEND_URL = "https://sabiway2025.vercel.app"
# BACKEND_URL = "https://django.sabiway.com"



# FRONTEND_URL = "https://sabiway2025.vercel.app"
# BACKEND_URL = "https://sabiway-9wq4.onrender.com"





GOOGLE_REDIRECT_URI = f"{BACKEND_URL}/api/auth/google-login/"


# ---------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    EXPRESS_URL,
    "http://localhost:3000",  # in case you test locally outside Docker
    "http://127.0.0.1:3000",
    "https://sabiway2025.vercel.app",
]
CORS_ALLOW_CREDENTIALS = True



# ---------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local apps
    "accounts",
    "docs",
    "profiles",
    "posts",
    "search",
    "notifications",

    # Third-party apps
    "rest_framework",
    'drf_yasg',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "cloudinary",
    "cloudinary_storage",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 👈 must be high up!
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]




ROOT_URLCONF = "sabiway.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sabiway.wsgi.application"

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Use DATABASE_URL from .env if available, otherwise SQLite

DATABASES = {
    "default": dj_database_url.parse(
        "postgresql://sabiway:wGSMPNQNTE6JQmJr1w565KXORm8frj7b@dpg-d4mh0o4hg0os73br7i1g-a.oregon-postgres.render.com/sabiway_cj9v",
        conn_max_age=600,
        ssl_require=True,  # Render PostgreSQL requires SSL
    )
}



# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ---------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------
STATIC_URL = "/static/"

# ---------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------
# Custom user model
# ---------------------------------------------------------------------
AUTH_USER_MODEL = "accounts.User"

# ---------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


# ---------------------------------------------------------------------
# Cloudinary
# ---------------------------------------------------------------------
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": "dk6ew5ikb",
    "API_KEY": "753545332897427",
    "API_SECRET": "ISyZy0BC8N7Lw870veJGhtIjx1A",
}

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

import cloudinary

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
    api_key=CLOUDINARY_STORAGE["API_KEY"],
    api_secret=CLOUDINARY_STORAGE["API_SECRET"]
)


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=3),   # 3 days
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),      # 90 days
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}