# Generated by Django 5.2.7 on 2025-10-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_image_reply_image'),
        ('profiles', '0004_profile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimpression',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='postimpression',
            name='posts_posti_post_id_48b1f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='postimpression',
            name='posts_posti_user_id_65815d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='postimpression',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postimpression',
            index=models.Index(fields=['user', 'post'], name='posts_posti_user_id_a5ff8a_idx'),
        ),
    ]
