# Generated by Django 5.2.7 on 2025-10-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postimpression_options_and_more'),
        ('profiles', '0004_profile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimpression',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='postimpression',
            name='posts_posti_user_id_a5ff8a_idx',
        ),
        migrations.RenameField(
            model_name='postimpression',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='postimpression',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postimpression',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimpression',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postimpression',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddConstraint(
            model_name='postimpression',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'post'), name='unique_user_post_impression'),
        ),
        migrations.AddConstraint(
            model_name='postimpression',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'post'), name='unique_session_post_impression'),
        ),
        migrations.AddConstraint(
            model_name='postimpression',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False)), fields=('ip_address', 'post'), name='unique_ip_post_impression'),
        ),
    ]
