# Generated by Django 5.2.7 on 2025-10-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_original_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
