"use client";

import { useState } from "react";
import { Eye, EyeOff, BriefcaseBusiness, UserRound } from "lucide-react";
import { FcGoogle } from "react-icons/fc";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import Link from "next/link";
import Image from "next/image";
import { useAuthStore, type AccountRole } from "@/app/store/useAuthStore";
import { DJANGO_URL } from "@/app/utils/MyConstants";

export default function Signup() {
  const [googleLoading, setGoogleLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const { signup, loading } = useAuthStore();
  const [form, setForm] = useState({ full_name: "", email: "", password: "", role: "client" as AccountRole, phone_number: "", terms_accepted: false }); const router = useRouter();
  const fieldClass = "w-full min-h-12 border border-[#d4dcd7] bg-white rounded-xl px-4 text-sm focus:ring-2 focus:ring-[#008753]/15 focus:border-[#008753] focus:outline-none";
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value })); };
  const handleSubmit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.terms_accepted) { toast.error("Accept the SabiWay Terms and Privacy Notice to continue."); return; } const success = await signup(form); if (success) router.push("/check-email"); };
  const handleGoogleLogin = async () => { setGoogleLoading(true); try { const res = await fetch(`${DJANGO_URL}/api/auth/generate-google-url/`); const data = await res.json(); if (data?.auth_url) window.location.href = data.auth_url; else toast.error("Failed to load Google login."); } catch { toast.error("Error initialising Google login"); } finally { setGoogleLoading(false); } };

  return <main className="min-h-screen bg-[#f4f5f4] text-[#173126] lg:grid lg:grid-cols-[.8fr_1.2fr]">
    <section className="hidden bg-[#008753] p-12 text-white lg:flex lg:flex-col lg:justify-between"><Link href="/" className="w-fit"><Image src="/Footerlogo.svg" alt="SabiWay" width={150} height={48} className="brightness-0 invert"/></Link><div><p className="text-xs font-black uppercase tracking-[.18em] text-white/65">Join SabiWay</p><h1 className="mt-4 max-w-lg text-5xl font-black leading-[1.02] tracking-[-.04em]">Choose how you want to use SabiWay.</h1><p className="mt-5 max-w-md text-base leading-7 text-white/75">Clients find trusted help. Professionals build visibility, trust and opportunities. Both stay connected through SabiForum.</p></div><p className="text-xs text-white/55">One account across web, Android and iOS</p></section>
    <section className="flex items-center justify-center px-4 py-10 sm:px-8"><div className="w-full max-w-xl"><Link href="/" className="mx-auto mb-8 block w-fit lg:hidden"><Image src="/Footerlogo.svg" alt="SabiWay" width={140} height={44}/></Link><p className="text-sm text-[#68776f]">Create your account</p><h2 className="mt-1 text-3xl font-black tracking-[-.025em]"><span className="text-[#008753]">Sign up</span> and start your journey with SabiWay.</h2>
      <form onSubmit={handleSubmit} className="mt-7 space-y-4"><fieldset><legend className="mb-2 text-sm font-bold">Select Your Role</legend><div className="grid grid-cols-2 gap-3">{([ ["professional", "Professional", BriefcaseBusiness], ["client", "Client", UserRound] ] as const).map(([role,label,Icon]) => <label key={role} className={`cursor-pointer rounded-2xl border p-5 text-center transition ${form.role === role ? "border-[#008753] bg-[#e7f7ef] shadow-sm" : "border-[#d5ddd8] bg-white"}`}><input type="radio" name="role" value={role} checked={form.role === role} onChange={() => setForm((current) => ({ ...current, role }))} className="sr-only"/><span className={`mx-auto flex h-12 w-12 items-center justify-center rounded-full ${form.role === role ? "bg-[#008753] text-white" : "bg-[#f1f3f2] text-[#66756d]"}`}><Icon size={21}/></span><span className="mt-3 block text-sm font-black">{label}</span></label>)}</div></fieldset>
        <label className="block text-sm font-bold">Full Name<input type="text" name="full_name" value={form.full_name} onChange={handleChange} required autoComplete="name" placeholder="Full Name" className={`${fieldClass} mt-1.5`}/></label><label className="block text-sm font-bold">Email Address<input type="email" name="email" value={form.email} onChange={handleChange} required autoComplete="email" placeholder="Email Address" className={`${fieldClass} mt-1.5`}/></label><label className="block text-sm font-bold">Phone Number <span className="font-normal text-[#7a867f]">(optional)</span><input type="tel" name="phone_number" value={form.phone_number} onChange={handleChange} autoComplete="tel" placeholder="08012345678 or +2348012345678" className={`${fieldClass} mt-1.5`}/></label><label className="block text-sm font-bold">Password<span className="relative mt-1.5 block"><input type={showPassword ? "text" : "password"} name="password" value={form.password} onChange={handleChange} required autoComplete="new-password" placeholder="Password" className={`${fieldClass} pr-12`}/><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#68776f]">{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></span></label>
        <label className="flex min-h-11 cursor-pointer items-start gap-3 text-sm leading-6"><input type="checkbox" checked={form.terms_accepted} onChange={(event) => setForm((current) => ({ ...current, terms_accepted: event.target.checked }))} className="mt-1 h-5 w-5 accent-[#008753]"/><span>I acknowledge that I have read and agree to the <Link href="/terms-of-use" className="font-bold text-[#008753]">SabiWay Agreements</Link> and <Link href="/privacy-policy" className="font-bold text-[#008753]">Privacy Policy</Link>.</span></label><button type="submit" disabled={loading} className="min-h-12 w-full rounded-xl bg-[#008753] text-sm font-black text-white disabled:opacity-60">{loading ? "Creating account…" : "Sign Up"}</button></form>
      <div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-[#dfe4e1]"/><span className="text-xs text-[#808a84]">or</span><span className="h-px flex-1 bg-[#dfe4e1]"/></div><button type="button" onClick={handleGoogleLogin} disabled={googleLoading} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-[#d4dcd7] bg-white text-sm font-bold disabled:opacity-60"><FcGoogle size={18}/>{googleLoading ? "Redirecting…" : "Continue with Google"}</button><p className="mt-6 text-center text-sm text-[#68776f]">I already have an account · <Link href="/login" className="font-black text-[#008753]">Sign in</Link></p></div></section>
  </main>;
}
