# Generated by Django 5.2.7 on 2025-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_address_profile_area_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
