export const PrivacyTOC = [
  { id: "definitions", label: "DEFINITIONS OF TERMS" },
  { id: "information_collected", label: "INFORMATION COLLECTED" },
  { id: "how_we_use", label: "HOW WE USE YOUR INFORMATION" },
  { id: "how_we_disclose", label: "HOW WE DISCLOSE YOUR INFORMATION" },
  { id: "payment_processing", label: "PAYMENT PROCESSING" },
  { id: "cookies", label: "COOKIES AND TRACKING TECHNOLOGIES" },
  { id: "data_security", label: "DATA SECURITY" },
  { id: "data_breach", label: "DATA BREACH NOTIFICATION" },
  { id: "retention", label: "RETENTION OF PERSONAL INFORMATION" },
  { id: "your_rights", label: "YOUR RIGHTS AND CHOICES" },
  { id: "jurisdiction_rights", label: "JURISDICTION-SPECIFIC RIGHTS" },
  { id: "automated_decision", label: "AUTOMATED DECISION-MAKING AND PROFILING" },
  { id: "international_transfers", label: "INTERNATIONAL DATA TRANSFERS" },
  { id: "third_party_links", label: "THIRD-PARTY LINKS AND SERVICES" },
  { id: "social_media", label: "SOCIAL MEDIA INTEGRATION" },
  { id: "communication_records", label: "COMMUNICATION RECORDS" },
  { id: "reviews_ratings", label: "REVIEWS AND RATINGS" },
  { id: "additional_professionals", label: "ADDITIONAL INFORMATION FOR SERVICE PROFESSIONALS" },
  { id: "childrens_privacy", label: "CHILDREN’S PRIVACY" },
  { id: "dispute_resolution", label: "DISPUTE RESOLUTION" },
  { id: "changes_policy", label: "CHANGES TO POLICY" },
  { id: "contact_us", label: "CONTACT US" },
];
